---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: validate-pr-review-app
archives:
  - id: app
    name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    formats: ["zip"]
    ids:
      - app
    files:
      - LICENSE
      - README.md
      - third_party_licenses/**/*
builds:
  - id: app
    binary: bootstrap
    main: cmd/app/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
sboms:
  - id: default
    disable: false
