---
name: Release
on:
  push:
    tags: [v*]
permissions: {}
jobs:
  release:
    uses: suzuki-shunsuke/go-release-workflow/.github/workflows/release.yaml@1cf29d7b17983b901021799b87a55d357cfff790 # v9.0.0
    with:
      go-version-file: go.mod
      aqua_version: v2.60.1
      go_licenses_package: ./cmd/app
    permissions:
      contents: write
      id-token: write
      actions: read
      attestations: write
    secrets:
      TAKUMI_GUARD_BOT_ID: ${{secrets.TAKUMI_GUARD_BOT_ID}}

  release-image:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.60.1

      - run: ko version
        env:
          AQUA_GITHUB_TOKEN: ${{ github.token }}
      - run: cosign version
        env:
          AQUA_GITHUB_TOKEN: ${{ github.token }}

      - run: echo "KO_DOCKER_REPO=ghcr.io/${GITHUB_REPOSITORY}" >> "$GITHUB_ENV"
      - run: ko build ./cmd/app --bare -t "$GITHUB_REF_NAME"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: docker pull "$KO_DOCKER_REPO:$GITHUB_REF_NAME"
      - run: |
          digest=$(docker inspect --format='{{index .RepoDigests 0}}' "$KO_DOCKER_REPO:$GITHUB_REF_NAME")
          echo "IMAGE_DIGEST=$digest" >> "$GITHUB_ENV"
      - run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "dummy" --password-stdin
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - run: cosign sign "$IMAGE_DIGEST"
